### ISSUE TITLE
기존 repo의 commit을 유지

### ISSUE THREAD

**Issue by SoheeJeong** [intelli8786/AI_BlemishesRemover#2]
기존 repo의 commit 내용들을 유지하면서 코드를 가져오면 어떨까요? 
그동안 코드를 commit과 pull request를 통해 관리했다는걸 어필하려면  이 방법이 좋을것같습니다.
또 나중에 부스트캠프 repo로 코드를 옮기고 기존 repo의 Integrated 브랜치를 삭제할 텐데 이때 기존 commit들이 삭제될것 같습니다.

임시로 temp 브랜치에 기존 commit이 반영된 코드를 가져와봤습니다.

**Comment by intelli8786** [comment]
좋은 생각입니다! Pull Request 걸어주세요!

**Comment by SoheeJeong** [comment]
오 pull request 가 안되네요..! 이전 commit들이 달라서 그런거같아요

**Comment by SoheeJeong** [comment]
설정에서 temp를 default branch 로 바꾸고 나중에 이름을 'master' 로 바꾸는 방법이 있을것같습니다

**Comment by intelli8786** [comment]
지금 main branch를 초기상태로 돌려볼까요?

**Comment by SoheeJeong** [comment]
오 네네! 그럼 그다음에 제가 다시 main으로 push할게요

**Comment by intelli8786** [comment]
지금 최초 시점으로 되돌렸습니다!

**Comment by SoheeJeong** [comment]
.gitignore 이랑 readme 가 남아있어서 push가 안되는거같아요! pull 도 안되네요 ㅠ

**Comment by SoheeJeong** [comment]
branch 이름을 바꾸고 default branch 로 설정하는게 좋을것같아요!

**Comment by intelli8786** [comment]
지금 main->default, temp->main 으로 변경했는데 잘 바뀌었나요?

**Comment by SoheeJeong** [comment]
네 branch 이름은 바뀌었습니다!

**Comment by SoheeJeong** [comment]
Settings/Branches 에서 default 브랜치를 main으로 지정할수 있을거같아요!

**Comment by intelli8786** [comment]
방금 변경했는데 한번 확인해보시겠어요?

**Comment by SoheeJeong** [comment]
오 변경되었네요!!

**Comment by SoheeJeong** [comment]
감사합니다~🤗

**Comment by intelli8786** [comment]
기존 레포에서 history까지 가져오는건 어떻게 하셨나요? 궁금하네요!

**Comment by SoheeJeong** [comment]
git remote remove origin 으로 기존 repo 의존성(??)을 없애고
git remote add origin <현재repo링크> 로 origin을 변경해줬어요!

**Comment by intelli8786** [comment]
오오 그렇군요!! 덕분에 많이 배웠어요!

**Comment by intelli8786** [comment]
이 이슈는 해결되었으니 닫도록 하겠습니다!
